[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# Fallback para SPA (React Router)
[[redirects]]
  from = "/api/*"
  to = "https://serviciosintegraless.netlify.app/api/:splat"
  status = 200
  force = true
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200